/**
 * Admin audit-trail routes (Phase 8, Part 4; docs/API_SPEC.md §2 admin).
 * Mounted under /api/v1/admin after requireAuth + requireRole("ADMIN"), so
 * everyone here is an authenticated admin. Read-only: there is deliberately no
 * endpoint that creates, updates or deletes audit events — the audit trail is
 * server-generated by the workflows themselves (docs/SECURITY.md §5,
 * docs/COMPLIANCE.md).
 */
import { Router } from "express";
import { z } from "zod";
import {
  AUDIT_ACTIONS,
  AUDIT_ENTITY_TYPES,
  type AuditEntityType,
  type AuditEventAction,
} from "@smartpark/shared";
import { asyncHandler } from "../../http/async-handler.js";
import { badRequest } from "../../http/errors.js";
import { auditService } from "./audit.service.js";

const actionSchema = z.enum(AUDIT_ACTIONS);
const entityTypeSchema = z.enum(AUDIT_ENTITY_TYPES);

function parseOptionalAction(raw: unknown): AuditEventAction | undefined {
  if (raw === undefined || raw === "") return undefined;
  const parsed = actionSchema.safeParse(raw);
  if (!parsed.success) {
    throw badRequest("VALIDATION_ERROR", "action must be one of: " + AUDIT_ACTIONS.join(", "));
  }
  return parsed.data;
}

function parseOptionalEntityType(raw: unknown): AuditEntityType | undefined {
  if (raw === undefined || raw === "") return undefined;
  const parsed = entityTypeSchema.safeParse(raw);
  if (!parsed.success) {
    throw badRequest(
      "VALIDATION_ERROR",
      "entityType must be one of: " + AUDIT_ENTITY_TYPES.join(", "),
    );
  }
  return parsed.data;
}

function parseOptionalPositiveInt(raw: unknown, name: string): number | undefined {
  if (raw === undefined || raw === "") return undefined;
  const value = typeof raw === "string" ? Number(raw) : Number.NaN;
  if (!Number.isInteger(value) || value <= 0) {
    throw badRequest("VALIDATION_ERROR", `${name} must be a positive integer`);
  }
  return value;
}

function parseOptionalIsoDate(raw: unknown, name: string): string | undefined {
  if (raw === undefined || raw === "") return undefined;
  if (typeof raw !== "string") {
    throw badRequest("VALIDATION_ERROR", `${name} must be a valid ISO-8601 timestamp`);
  }
  const date = new Date(raw);
  if (Number.isNaN(date.getTime())) {
    throw badRequest("VALIDATION_ERROR", `${name} must be a valid ISO-8601 timestamp`);
  }
  return date.toISOString();
}

export const auditRouter = Router();

auditRouter.get(
  "/audit-events",
  asyncHandler(async (req, res) => {
    res.json(
      await auditService.listEvents({
        action: parseOptionalAction(req.query.action),
        entityType: parseOptionalEntityType(req.query.entityType),
        actorUserId: parseOptionalPositiveInt(req.query.actorUserId, "actorUserId"),
        entityId: parseOptionalPositiveInt(req.query.entityId, "entityId"),
        from: parseOptionalIsoDate(req.query.from, "from"),
        to: parseOptionalIsoDate(req.query.to, "to"),
        page: parseOptionalPositiveInt(req.query.page, "page"),
        limit: parseOptionalPositiveInt(req.query.limit, "limit"),
      }),
    );
  }),
);
